/*
 * Copyright 2004, 2005, 2006 PathScale, Inc.  All Rights Reserved.
 */

/*

  Copyright (C) 2000, 2001, Silicon Graphics, Inc.  All Rights Reserved.

   Path64 is free software; you can redistribute it and/or modify it
   under the terms of the GNU Lesser General Public License as published by
   the Free Software Foundation version 2.1

   Path64 is distributed in the hope that it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with Path64; see the file COPYING.  If not, write to the Free
   Software Foundation, 51 Franklin Street, Fifth Floor, Boston, MA
   02110-1301, USA.

   Special thanks goes to SGI for their continued support to open source

*/

#include <stdlib.h>


#pragma ident "@(#) libf/fio/main.c	92.1	11/16/99 15:43:33"
/*
 * Use main to get to the MAIN__ entry point generated by the
 * Fortran 90 compiler on mips and on some little endian systems.
 * In the future, do not use the libF77 routine with Fortran 90.
 */
#if     defined(__linux) || defined(BUILD_OS_DARWIN)
extern void MAIN__(void);

extern void __f90_set_args(int argc, char **argv);

int __f90_main(int argc, char **argv, char **arge)
{
	__f90_set_args(argc, argv);

        MAIN__();
        exit(0);
        return (0);
}

#if 0
typeof(__f90_main) main __attribute__((weak, alias("__f90_main")));
#endif

#endif
