/* This file is machine generated.  Do not edit.  */

/* Here is the logic for how this file was supposed to be generated
 */
/*
gtyp-gen.h: s-gtyp-gen ; @true
s-gtyp-gen: Makefile
        echo "static const char *const srcdir = "  >> tmp-gtyp.h
        echo "\"$(GTFILES_SRCDIR)\"" >> tmp-gtyp.h
        echo ";" >> tmp-gtyp.h
        echo "static const char *const lang_files[] = {" >> tmp-gtyp.h
        $(foreach gtyp,$(GTFILES_FILES_FILES),$(echo_quoted_to_gtyp))
        echo "NULL};" >> tmp-gtyp.h
        echo "static const char *const langs_for_lang_files[] = {" >> tmp-gtyp.h
        $(foreach gtyp,$(GTFILES_FILES_LANGS),$(echo_quoted_to_gtyp))
        echo "NULL};" >> tmp-gtyp.h
        echo "static const char *const all_files[] = {" >> tmp-gtyp.h
        $(foreach gtyp,$(GTFILES),$(echo_quoted_to_gtyp))
        echo " NULL};" >> tmp-gtyp.h
        echo "static const char *const lang_dir_names[] = { \"c\", " >> tmp-gtyp.h
        $(foreach gtyp,$(GTFILES_LANG_DIR_NAMES),$(echo_quoted_to_gtyp))
        echo "NULL};" >> tmp-gtyp.h
        $(SHELL) $(srcdir)/../move-if-change tmp-gtyp.h gtyp-gen.h
        $(STAMP) s-gtyp-gen
*/
static const char *const srcdir = 
"../../gcc"
;
static const char *const lang_files[] = {
"../../gcc/cp/rtti.c", 
"../../gcc/cp/mangle.c", 
"../../gcc/cp/name-lookup.h", 
"../../gcc/cp/name-lookup.c", 
"../../gcc/cp/cp-tree.h", 
"../../gcc/cp/decl.h", 
"../../gcc/cp/call.c", 
"../../gcc/cp/decl.c", 
"../../gcc/cp/decl2.c", 
"../../gcc/cp/pt.c", 
"../../gcc/cp/repo.c", 
"../../gcc/cp/semantics.c", 
"../../gcc/cp/tree.c", 
"../../gcc/cp/parser.c", 
"../../gcc/cp/method.c", 
"../../gcc/cp/typeck2.c", 
"../../gcc/c-common.c", 
"../../gcc/c-common.h", 
"../../gcc/c-lex.c", 
"../../gcc/c-pragma.c", 
"../../gcc/cp/class.c", 
"../../gcc/cp/cp-objcp-common.c", 
"../../gcc/c-lang.c", 
"../../gcc/c-tree.h", 
"../../gcc/c-decl.c", 
"../../gcc/c-common.c", 
"../../gcc/c-common.h", 
"../../gcc/c-pragma.c", 
"../../gcc/c-objc-common.c", 
"../../gcc/c-parser.c", 
NULL};
static const char *const langs_for_lang_files[] = {
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"cp", 
"c", 
"c", 
"c", 
"c", 
"c", 
"c", 
"c", 
"c", 
NULL};
static const char *const all_files[] = {
"../../gcc/input.h", 
"../../gcc/coretypes.h", 
"../../gcc/../libcpp/include/line-map.h", 
"../../gcc/../libcpp/include/cpplib.h", 
"../../gcc/../libcpp/include/cpp-id-data.h", 
"auto-host.h", 
"../../gcc/../include/ansidecl.h", 
"options.h", 
"../../gcc/config/i386/biarch64.h", 
"../../gcc/config/i386/i386.h", 
"../../gcc/config/i386/unix.h", 
"../../gcc/config/i386/att.h", 
"../../gcc/config/dbxelf.h", 
"../../gcc/config/elfos.h", 
"../../gcc/config/svr4.h", 
"../../gcc/config/linux.h", 
"../../gcc/config/i386/x86-64.h", 
"../../gcc/config/i386/linux64.h", 
"../../gcc/defaults.h", 
"../../gcc/../include/hashtab.h", 
"../../gcc/../include/splay-tree.h", 
"../../gcc/bitmap.h", 
"../../gcc/coverage.c", 
"../../gcc/rtl.h", 
"../../gcc/optabs.h", 
"../../gcc/tree.h", 
"../../gcc/function.h", 
"../../gcc/libfuncs.h", 
"../../gcc/../libcpp/include/symtab.h", 
"../../gcc/real.h", 
"../../gcc/varray.h", 
"../../gcc/insn-addr.h", 
"../../gcc/hwint.h", 
"../../gcc/ipa-reference.h", 
"../../gcc/output.h", 
"../../gcc/cselib.h", 
"../../gcc/basic-block.h", 
"../../gcc/cgraph.h", 
"../../gcc/c-common.h", 
"../../gcc/c-tree.h", 
"../../gcc/reload.h", 
"../../gcc/alias.c", 
"../../gcc/bitmap.c", 
"../../gcc/cselib.c", 
"../../gcc/cgraph.c", 
"../../gcc/ipa-prop.c", 
"../../gcc/ipa-cp.c", 
"../../gcc/ipa-inline.c", 
"../../gcc/dbxout.c", 
"../../gcc/dwarf2out.c", 
"../../gcc/dwarf2asm.c", 
"../../gcc/dojump.c", 
"../../gcc/tree-profile.c", 
"../../gcc/emit-rtl.c", 
"../../gcc/except.c", 
"../../gcc/explow.c", 
"../../gcc/expr.c", 
"../../gcc/function.c", 
"../../gcc/except.h", 
"../../gcc/gcse.c", 
"../../gcc/integrate.c", 
"../../gcc/lists.c", 
"../../gcc/optabs.c", 
"../../gcc/profile.c", 
"../../gcc/regclass.c", 
"../../gcc/reg-stack.c", 
"../../gcc/cfglayout.c", 
"../../gcc/sdbout.c", 
"../../gcc/stor-layout.c", 
"../../gcc/stringpool.c", 
"../../gcc/tree.c", 
"../../gcc/varasm.c", 
"../../gcc/tree-mudflap.c", 
"../../gcc/tree-flow.h", 
"../../gcc/c-objc-common.c", 
"../../gcc/c-common.c", 
"../../gcc/c-parser.c", 
"../../gcc/tree-ssanames.c", 
"../../gcc/tree-eh.c", 
"../../gcc/tree-ssa-address.c", 
"../../gcc/tree-phinodes.c", 
"../../gcc/tree-cfg.c", 
"../../gcc/tree-dfa.c", 
"../../gcc/tree-ssa-propagate.c", 
"../../gcc/tree-iterator.c", 
"../../gcc/gimplify.c", 
"../../gcc/tree-chrec.h", 
"../../gcc/tree-vect-generic.c", 
"../../gcc/tree-ssa-operands.h", 
"../../gcc/tree-ssa-operands.c", 
"../../gcc/tree-profile.c", 
"../../gcc/tree-nested.c", 
"../../gcc/ipa-reference.c", 
"../../gcc/tree-ssa-structalias.h", 
"../../gcc/tree-ssa-structalias.c", 
"../../gcc/c-pragma.h", 
"../../gcc/omp-low.c", 
"../../gcc/targhooks.c", 
"../../gcc/cgraphunit.c", 
"../../gcc/config/i386/i386.c", 
"../../gcc/cp/rtti.c", 
"../../gcc/cp/mangle.c", 
"../../gcc/cp/name-lookup.h", 
"../../gcc/cp/name-lookup.c", 
"../../gcc/cp/cp-tree.h", 
"../../gcc/cp/decl.h", 
"../../gcc/cp/call.c", 
"../../gcc/cp/decl.c", 
"../../gcc/cp/decl2.c", 
"../../gcc/cp/pt.c", 
"../../gcc/cp/repo.c", 
"../../gcc/cp/semantics.c", 
"../../gcc/cp/tree.c", 
"../../gcc/cp/parser.c", 
"../../gcc/cp/method.c", 
"../../gcc/cp/typeck2.c", 
"../../gcc/c-common.c", 
"../../gcc/c-common.h", 
"../../gcc/c-lex.c", 
"../../gcc/c-pragma.c", 
"../../gcc/cp/class.c", 
"../../gcc/cp/cp-objcp-common.c", 
"../../gcc/c-lang.c", 
"../../gcc/c-tree.h", 
"../../gcc/c-decl.c", 
"../../gcc/c-common.c", 
"../../gcc/c-common.h", 
"../../gcc/c-pragma.c", 
"../../gcc/c-objc-common.c", 
"../../gcc/c-parser.c", 
 NULL};
static const char *const lang_dir_names[] = { "c", 
"cp", 
NULL};
